### ISSUE TITLE
Replugging the board does not work

### ISSUE THREAD

**Issue by olivierbrcknr** [olivierbrcknr/blokdots-app_dev#49]
Once the board are set up within the live view, then the board unplugged and replugged again, the board does not work anymore, even though recognised and initiated.

We should reset the board when unplugged and reinitiate the board and each component again. 
Maybe the new init is recognised as a new board and not the previous one?

**Comment by olivierbrcknr** [comment]
So, I guess the issue is, that the board is terminated if event `close` is fired.

```jsx
this.board.on("close", () => {
  console.info('🚪 Board closed');
  this.terminateBoard();
});
```

But `close` will be fired *through* the `terminateBoard()` function. So we need to insert `this.terminateBoard()` where the board needs to be closed and only log the info, only for feedback if it actually worked.

**Comment by ChristophLabacher** [comment]
Another problem could be that we listen for a "close" event, from Johnny-5, but I don’t think there is one: http://johnny-five.io/api/board/#events

**Comment by olivierbrcknr** [comment]
That's why we have the `terminateBoard()`. With this one we look into the io dependency and manually close the serialport. So actually the whole `close` event listener is redundant. 

```jsx
terminateBoard() {
  // Close serial port within the firmata object within johnny-5 object
  if (this.board && this.board.io && this.board.io.transport && this.board.io.transport.isOpen) {
    this.board.io.transport.close(() => {
      this.resetBoardProperties();
      console.log('🔑 Board and serial port closed');
    });
  }

  this.port = undefined;
  this.referenceToStore.dispatch(setBoardIsReady(false));
}
```

**Comment by olivierbrcknr** [comment]
So closing and reconnecting seems to work, "simply" setting up the components again does not. 
@ChristophLabacher – *Question 1:* Do we currently delete all component variables?

Within the old code, I also assigned to every j5 component the specific board, to prevent issues of connecting to the wrong / previous object.
```js
window[ slotObj.var ] = new five.Sensor({
  pin       : slotObj.slot,
  board     : board
});
```
*Question 2:* Should we consider to also include that piece when setting up the components in the hardwareComponents index files?

**Comment by olivierbrcknr** [comment]
Ok tried replugging it again, but still does not reconnect the components.
Do we delete the old boards?

**Comment by ChristophLabacher** [comment]
I think we need to restructure the terminateBoard function. Will take a look later …

**Comment by ChristophLabacher** [comment]
After some extensive logging I think the problem is that Johnny Five is keeping it’s own instance of the board variable around and is adding newly registered components to the old board, even though we set it to undefined before.

**Comment by ChristophLabacher** [comment]
This still happens when I pass in the board in the constructor of the component, as you have show.

**Comment by ChristophLabacher** [comment]
found the mistake, passing it in the constructer does work. my bad.

**Comment by ChristophLabacher** [comment]
@olivierbrcknr please check if the issue has been fixed

**Comment by ChristophLabacher** [comment]
Or maybe it has, but now there is a different problem with PWM slots

**Comment by ChristophLabacher** [comment]
Just a stupid typo
